# Generated by Django 5.0.6 on 2026-08-25 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('http_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('connection_error', 'Connection Error'), ('dns_error', 'DNS Resolution Error'), ('ssl_error', 'SSL/TLS Error'), ('http_error', 'Unexpected HTTP Status'), ('too_many_redirects', 'Too Many Redirects'), ('unknown', 'Unknown Error')], default='none', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('monitor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='monitors.monitor')),
            ],
            options={
                'db_table': 'checks_checkresult',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='idx_checkresult_monitor_time'), models.Index(fields=['checked_at'], name='idx_checkresult_time')],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('up_checks', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('uptime_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('incident_count', models.PositiveSmallIntegerField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='monitors.monitor')),
            ],
            options={
                'db_table': 'checks_dailystats',
                'indexes': [models.Index(fields=['monitor', '-date'], name='idx_dailystats_monitor_date')],
                'unique_together': {('monitor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('up_checks', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('uptime_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='monitors.monitor')),
            ],
            options={
                'db_table': 'checks_hourlystats',
                'indexes': [models.Index(fields=['monitor', '-hour'], name='idx_hourlystats_monitor_hour')],
                'unique_together': {('monitor', 'hour')},
            },
        ),
    ]
