# Generated by Django 5.0.6 on 2026-08-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='error_type',
            field=models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('connection_error', 'Connection Error'), ('dns_error', 'DNS Resolution Error'), ('ssl_error', 'SSL/TLS Error'), ('http_error', 'Unexpected HTTP Status'), ('too_many_redirects', 'Too Many Redirects'), ('keyword_missing', 'Keyword Missing'), ('keyword_present', 'Forbidden Keyword Found'), ('ssl_expiring_soon', 'SSL Certificate Expiring Soon'), ('ssl_expired', 'SSL Certificate Expired'), ('domain_expiring_soon', 'Domain Expiring Soon'), ('domain_expired', 'Domain Registration Expired'), ('tcp_connection_failed', 'TCP Port Connection Failed'), ('unknown', 'Unknown Error')], default='none', max_length=30),
        ),
    ]
