# Generated by Django 5.0.6 on 2026-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_alter_checkresult_error_type'),
        ('monitors', '0003_monitor_quorum_threshold_monitor_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='region',
            field=models.CharField(db_index=True, default='eu-central', max_length=32),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['monitor', 'region', '-checked_at'], name='idx_checkresult_mon_reg_time'),
        ),
    ]
