# Generated by Django 5.0.6 on 2026-08-25 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('failure_count', models.PositiveIntegerField(default=1)),
                ('root_cause_error', models.CharField(blank=True, help_text='CheckErrorType from the first failing check.', max_length=50)),
                ('root_cause_message', models.TextField(blank=True, help_text='Error message from the first failing check — immutable snapshot.')),
                ('alert_sent', models.BooleanField(default=False)),
                ('resolved_alert_sent', models.BooleanField(default=False)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
            options={
                'db_table': 'incidents_incident',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['monitor', 'is_resolved'], name='idx_incident_monitor_resolved'), models.Index(fields=['started_at'], name='idx_incident_started')],
            },
        ),
    ]
