# Generated by Django 5.0.6 on 2026-08-25 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('PUT', 'PUT')], default='GET', max_length=10)),
                ('expected_status_code', models.PositiveSmallIntegerField(default=200)),
                ('interval', models.PositiveIntegerField(choices=[(30, '30 seconds'), (60, '1 minute'), (300, '5 minutes'), (900, '15 minutes')], db_index=True, default=60)),
                ('timeout', models.PositiveSmallIntegerField(default=10)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('current_status', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down'), ('paused', 'Paused')], db_index=True, default='unknown', max_length=10)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('failure_threshold', models.PositiveSmallIntegerField(default=3, help_text='Number of consecutive failures before opening an incident.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, help_text='Used for /status/<slug>/ public page.', max_length=80, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitors_monitor',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['interval', 'is_active'], name='idx_monitor_interval_active'), models.Index(fields=['owner', 'current_status'], name='idx_monitor_owner_status')],
            },
        ),
    ]
