# Generated by Django 5.0.6 on 2026-08-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='domain_threshold_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days remaining before domain registration expiration to alert.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='keyword',
            field=models.CharField(blank=True, help_text='Expected substring or regex on the target page (for KEYWORD check).', max_length=255),
        ),
        migrations.AddField(
            model_name='monitor',
            name='keyword_should_exist',
            field=models.BooleanField(default=True, help_text='If True, monitor is DOWN if keyword is missing. If False, DOWN if keyword is present.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_type',
            field=models.CharField(choices=[('http', 'HTTP(s) Status'), ('keyword', 'Keyword / Content'), ('ssl', 'SSL / TLS Certificate'), ('tcp', 'TCP Port Ping'), ('domain', 'Domain Expiry')], db_index=True, default='http', max_length=20),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ssl_threshold_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Days remaining before SSL cert expiration to mark monitor DOWN/Warning.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='tcp_port',
            field=models.PositiveIntegerField(blank=True, help_text='Target port for TCP ping check (e.g. 5432, 6379, 80).', null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.CharField(help_text='Target URL or hostname / IP for TCP.', max_length=2000),
        ),
    ]
