# Generated by Django 5.0.6 on 2026-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitor_domain_threshold_days_monitor_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='quorum_threshold',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of regions that must concurrently report DOWN to open an incident.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='regions',
            field=models.JSONField(blank=True, default=list, help_text="List of region slugs (e.g. ['eu-central', 'us-east']). Empty defaults to ['eu-central']."),
        ),
    ]
