# Generated by Django 5.0.6 on 2026-08-25 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('slack', 'Slack')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_alertchannel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='notifications.alertchannel')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to='monitors.monitor')),
            ],
            options={
                'db_table': 'notifications_monitoralert',
            },
        ),
        migrations.AddIndex(
            model_name='alertchannel',
            index=models.Index(fields=['owner', 'channel_type'], name='idx_channel_owner_type'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoralert',
            unique_together={('monitor', 'channel')},
        ),
    ]
